# Generated by Django 3.1.2 on 2020-10-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfaces',
            options={'verbose_name': '接口', 'verbose_name_plural': '接口'},
        ),
    ]
