# Generated by Django 3.1.2 on 2020-11-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='publish_app',
            field=models.CharField(blank=True, default='', help_text='发布应用', max_length=100, null=True, verbose_name='发布应用'),
        ),
    ]
