# Generated by Django 3.1.2 on 2020-10-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201029_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
